spark:
  appName: SparkStreamingLogAggregationApp
  duration: 2000
kafkaConnection:
  group: test
  topics:
    logstopic: 1
  zookeeper: sandbox.hortonworks.com:2181
hbase:
  tableName: LOGS_I
  columnFamily: LG
  zookeeperClientPort: 2181
  zookeeperQuorum: sandbox.hortonworks.com
  zookeeperParent: /hbase-unsecure
hadoop:
  fileSystem: hdfs://sandbox.hortonworks.com:8020/
  cityDictionary: hdfs://sandbox.hortonworks.com:8020/tmp/admin/cities/city.txt
  tagDictionary: hdfs://sandbox.hortonworks.com:8020/tmp/admin/tags/user.profile.tags.us.tag.txt
elasticSearch:
  index: logs03
  type: logs


