spark:
  appName: SparkStreamingLogAggregationApp
  duration: 2000
kafkaConnection:
  group: test
  topics:
    logs-topic: 1
  zookeeper: sandbox.hortonworks.com:2181
hbase:
  tableName: L_DATA
  columnFamily: COL
  zookeeperClientPort: 2181
  zookeeperQuorum: sandbox.hortonworks.com
  zookeeperParent: /hbase-unsecure
hadoop:
  fileSystem: hdfs://sandbox.hortonworks.com:8020/
  cityDictionary: hdfs://sandbox.hortonworks.com:8020/tmp/admin/cities/city.txt
elasticSearch:
  index: logs03
  type: logs


